/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsGetActionsCacheUsageByRepoForOrg200Response {
    #[serde(rename = "total_count")]
    pub total_count: i32,
    #[serde(rename = "repository_cache_usages")]
    pub repository_cache_usages: Vec<models::ActionsCacheUsageByRepository>,
}

impl ActionsGetActionsCacheUsageByRepoForOrg200Response {
    pub fn new(total_count: i32, repository_cache_usages: Vec<models::ActionsCacheUsageByRepository>) -> ActionsGetActionsCacheUsageByRepoForOrg200Response {
        ActionsGetActionsCacheUsageByRepoForOrg200Response {
            total_count,
            repository_cache_usages,
        }
    }
}

