/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsGenerateRunnerJitconfigForOrg201Response {
    #[serde(rename = "runner")]
    pub runner: Box<models::Runner>,
    /// The base64 encoded runner configuration.
    #[serde(rename = "encoded_jit_config")]
    pub encoded_jit_config: String,
}

impl ActionsGenerateRunnerJitconfigForOrg201Response {
    pub fn new(runner: models::Runner, encoded_jit_config: String) -> ActionsGenerateRunnerJitconfigForOrg201Response {
        ActionsGenerateRunnerJitconfigForOrg201Response {
            runner: Box::new(runner),
            encoded_jit_config,
        }
    }
}

