/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsSetSelectedRepositoriesEnabledGithubActionsOrganizationRequest {
    /// List of repository IDs to enable for GitHub Actions.
    #[serde(rename = "selected_repository_ids")]
    pub selected_repository_ids: Vec<i32>,
}

impl ActionsSetSelectedRepositoriesEnabledGithubActionsOrganizationRequest {
    pub fn new(selected_repository_ids: Vec<i32>) -> ActionsSetSelectedRepositoriesEnabledGithubActionsOrganizationRequest {
        ActionsSetSelectedRepositoriesEnabledGithubActionsOrganizationRequest {
            selected_repository_ids,
        }
    }
}

