/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsSetGithubActionsPermissionsRepositoryRequest {
    /// Whether GitHub Actions is enabled on the repository.
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "allowed_actions", skip_serializing_if = "Option::is_none")]
    pub allowed_actions: Option<models::AllowedActions>,
}

impl ActionsSetGithubActionsPermissionsRepositoryRequest {
    pub fn new(enabled: bool) -> ActionsSetGithubActionsPermissionsRepositoryRequest {
        ActionsSetGithubActionsPermissionsRepositoryRequest {
            enabled,
            allowed_actions: None,
        }
    }
}

