/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsReRunJobForWorkflowRunRequest {
    /// Whether to enable debug logging for the re-run.
    #[serde(rename = "enable_debug_logging", skip_serializing_if = "Option::is_none")]
    pub enable_debug_logging: Option<bool>,
}

impl ActionsReRunJobForWorkflowRunRequest {
    pub fn new() -> ActionsReRunJobForWorkflowRunRequest {
        ActionsReRunJobForWorkflowRunRequest {
            enable_debug_logging: None,
        }
    }
}

