/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsSetGithubActionsPermissionsOrganizationRequest {
    #[serde(rename = "enabled_repositories")]
    pub enabled_repositories: models::EnabledRepositories,
    #[serde(rename = "allowed_actions", skip_serializing_if = "Option::is_none")]
    pub allowed_actions: Option<models::AllowedActions>,
}

impl ActionsSetGithubActionsPermissionsOrganizationRequest {
    pub fn new(enabled_repositories: models::EnabledRepositories) -> ActionsSetGithubActionsPermissionsOrganizationRequest {
        ActionsSetGithubActionsPermissionsOrganizationRequest {
            enabled_repositories,
            allowed_actions: None,
        }
    }
}

