/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsCacheUsageOrgEnterprise {
    /// The count of active caches across all repositories of an enterprise or an organization.
    #[serde(rename = "total_active_caches_count")]
    pub total_active_caches_count: i32,
    /// The total size in bytes of all active cache items across all repositories of an enterprise or an organization.
    #[serde(rename = "total_active_caches_size_in_bytes")]
    pub total_active_caches_size_in_bytes: i32,
}

impl ActionsCacheUsageOrgEnterprise {
    pub fn new(total_active_caches_count: i32, total_active_caches_size_in_bytes: i32) -> ActionsCacheUsageOrgEnterprise {
        ActionsCacheUsageOrgEnterprise {
            total_active_caches_count,
            total_active_caches_size_in_bytes,
        }
    }
}

