/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiOverviewDomains {
    #[serde(rename = "website", skip_serializing_if = "Option::is_none")]
    pub website: Option<Vec<String>>,
    #[serde(rename = "codespaces", skip_serializing_if = "Option::is_none")]
    pub codespaces: Option<Vec<String>>,
    #[serde(rename = "copilot", skip_serializing_if = "Option::is_none")]
    pub copilot: Option<Vec<String>>,
    #[serde(rename = "packages", skip_serializing_if = "Option::is_none")]
    pub packages: Option<Vec<String>>,
    #[serde(rename = "actions", skip_serializing_if = "Option::is_none")]
    pub actions: Option<Vec<String>>,
}

impl ApiOverviewDomains {
    pub fn new() -> ApiOverviewDomains {
        ApiOverviewDomains {
            website: None,
            codespaces: None,
            copilot: None,
            packages: None,
            actions: None,
        }
    }
}

