/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppsListReposAccessibleToInstallation200Response {
    #[serde(rename = "total_count")]
    pub total_count: i32,
    #[serde(rename = "repositories")]
    pub repositories: Vec<models::Repository>,
    #[serde(rename = "repository_selection", skip_serializing_if = "Option::is_none")]
    pub repository_selection: Option<String>,
}

impl AppsListReposAccessibleToInstallation200Response {
    pub fn new(total_count: i32, repositories: Vec<models::Repository>) -> AppsListReposAccessibleToInstallation200Response {
        AppsListReposAccessibleToInstallation200Response {
            total_count,
            repositories,
            repository_selection: None,
        }
    }
}

