/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppsCreateInstallationAccessTokenRequest {
    /// List of repository names that the token should have access to
    #[serde(rename = "repositories", skip_serializing_if = "Option::is_none")]
    pub repositories: Option<Vec<String>>,
    /// List of repository IDs that the token should have access to
    #[serde(rename = "repository_ids", skip_serializing_if = "Option::is_none")]
    pub repository_ids: Option<Vec<i32>>,
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Box<models::AppPermissions>>,
}

impl AppsCreateInstallationAccessTokenRequest {
    pub fn new() -> AppsCreateInstallationAccessTokenRequest {
        AppsCreateInstallationAccessTokenRequest {
            repositories: None,
            repository_ids: None,
            permissions: None,
        }
    }
}

