/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BranchProtectionLockBranch : Whether to set the branch as read-only. If this is true, users will not be able to push to the branch.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BranchProtectionLockBranch {
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl BranchProtectionLockBranch {
    /// Whether to set the branch as read-only. If this is true, users will not be able to push to the branch.
    pub fn new() -> BranchProtectionLockBranch {
        BranchProtectionLockBranch {
            enabled: None,
        }
    }
}

