/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChecksCreateSuiteRequest {
    /// The sha of the head commit.
    #[serde(rename = "head_sha")]
    pub head_sha: String,
}

impl ChecksCreateSuiteRequest {
    pub fn new(head_sha: String) -> ChecksCreateSuiteRequest {
        ChecksCreateSuiteRequest {
            head_sha,
        }
    }
}

