/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChecksSetSuitesPreferencesRequest {
    /// Enables or disables automatic creation of CheckSuite events upon pushes to the repository. Enabled by default.
    #[serde(rename = "auto_trigger_checks", skip_serializing_if = "Option::is_none")]
    pub auto_trigger_checks: Option<Vec<models::ChecksSetSuitesPreferencesRequestAutoTriggerChecksInner>>,
}

impl ChecksSetSuitesPreferencesRequest {
    pub fn new() -> ChecksSetSuitesPreferencesRequest {
        ChecksSetSuitesPreferencesRequest {
            auto_trigger_checks: None,
        }
    }
}

