/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodespacesPublishForAuthenticatedUserRequest {
    /// A name for the new repository.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Whether the new repository should be private.
    #[serde(rename = "private", skip_serializing_if = "Option::is_none")]
    pub private: Option<bool>,
}

impl CodespacesPublishForAuthenticatedUserRequest {
    pub fn new() -> CodespacesPublishForAuthenticatedUserRequest {
        CodespacesPublishForAuthenticatedUserRequest {
            name: None,
            private: None,
        }
    }
}

