/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodespaceRuntimeConstraints {
    /// The privacy settings a user can select from when forwarding a port.
    #[serde(rename = "allowed_port_privacy_settings", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub allowed_port_privacy_settings: Option<Option<Vec<String>>>,
}

impl CodespaceRuntimeConstraints {
    pub fn new() -> CodespaceRuntimeConstraints {
        CodespaceRuntimeConstraints {
            allowed_port_privacy_settings: None,
        }
    }
}

