/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CodespacesCreateForAuthenticatedUserRequestOneOf1PullRequest : Pull request number for this codespace
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodespacesCreateForAuthenticatedUserRequestOneOf1PullRequest {
    /// Pull request number
    #[serde(rename = "pull_request_number")]
    pub pull_request_number: i32,
    /// Repository id for this codespace
    #[serde(rename = "repository_id")]
    pub repository_id: i32,
}

impl CodespacesCreateForAuthenticatedUserRequestOneOf1PullRequest {
    /// Pull request number for this codespace
    pub fn new(pull_request_number: i32, repository_id: i32) -> CodespacesCreateForAuthenticatedUserRequestOneOf1PullRequest {
        CodespacesCreateForAuthenticatedUserRequestOneOf1PullRequest {
            pull_request_number,
            repository_id,
        }
    }
}

