/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodespacesListDevcontainersInRepositoryForAuthenticatedUser200ResponseDevcontainersInner {
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
}

impl CodespacesListDevcontainersInRepositoryForAuthenticatedUser200ResponseDevcontainersInner {
    pub fn new(path: String) -> CodespacesListDevcontainersInRepositoryForAuthenticatedUser200ResponseDevcontainersInner {
        CodespacesListDevcontainersInRepositoryForAuthenticatedUser200ResponseDevcontainersInner {
            path,
            name: None,
            display_name: None,
        }
    }
}

