/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CodeOfConductSimple : Code of Conduct Simple
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodeOfConductSimple {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "html_url", deserialize_with = "Option::deserialize")]
    pub html_url: Option<String>,
}

impl CodeOfConductSimple {
    /// Code of Conduct Simple
    pub fn new(url: String, key: String, name: String, html_url: Option<String>) -> CodeOfConductSimple {
        CodeOfConductSimple {
            url,
            key,
            name,
            html_url,
        }
    }
}

