/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodespacesSetSelectedReposForOrgSecretRequest {
    /// An array of repository ids that can access the organization secret. You can only provide a list of repository ids when the `visibility` is set to `selected`. You can add and remove individual repositories using the [Set selected repositories for an organization secret](https://docs.github.com/rest/codespaces/organization-secrets#set-selected-repositories-for-an-organization-secret) and [Remove selected repository from an organization secret](https://docs.github.com/rest/codespaces/organization-secrets#remove-selected-repository-from-an-organization-secret) endpoints.
    #[serde(rename = "selected_repository_ids")]
    pub selected_repository_ids: Vec<i32>,
}

impl CodespacesSetSelectedReposForOrgSecretRequest {
    pub fn new(selected_repository_ids: Vec<i32>) -> CodespacesSetSelectedReposForOrgSecretRequest {
        CodespacesSetSelectedReposForOrgSecretRequest {
            selected_repository_ids,
        }
    }
}

