/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodespacesRepoMachinesForAuthenticatedUser200Response {
    #[serde(rename = "total_count")]
    pub total_count: i32,
    #[serde(rename = "machines")]
    pub machines: Vec<models::CodespaceMachine>,
}

impl CodespacesRepoMachinesForAuthenticatedUser200Response {
    pub fn new(total_count: i32, machines: Vec<models::CodespaceMachine>) -> CodespacesRepoMachinesForAuthenticatedUser200Response {
        CodespacesRepoMachinesForAuthenticatedUser200Response {
            total_count,
            machines,
        }
    }
}

