/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CommitActivity : Commit Activity
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommitActivity {
    #[serde(rename = "days")]
    pub days: Vec<i32>,
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "week")]
    pub week: i32,
}

impl CommitActivity {
    /// Commit Activity
    pub fn new(days: Vec<i32>, total: i32, week: i32) -> CommitActivity {
        CommitActivity {
            days,
            total,
            week,
        }
    }
}

