/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContributorActivity : Contributor Activity
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContributorActivity {
    #[serde(rename = "author", deserialize_with = "Option::deserialize")]
    pub author: Option<Box<models::NullableSimpleUser>>,
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "weeks")]
    pub weeks: Vec<models::ContributorActivityWeeksInner>,
}

impl ContributorActivity {
    /// Contributor Activity
    pub fn new(author: Option<models::NullableSimpleUser>, total: i32, weeks: Vec<models::ContributorActivityWeeksInner>) -> ContributorActivity {
        ContributorActivity {
            author: if let Some(x) = author {Some(Box::new(x))} else {None},
            total,
            weeks,
        }
    }
}

