/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CopilotSeatDetails : Information about a Copilot Business seat assignment for a user, team, or organization.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CopilotSeatDetails {
    #[serde(rename = "assignee")]
    pub assignee: Box<models::CopilotSeatDetailsAssignee>,
    #[serde(rename = "assigning_team", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub assigning_team: Option<Option<Box<models::CopilotSeatDetailsAssigningTeam>>>,
    /// The pending cancellation date for the seat, in `YYYY-MM-DD` format. This will be null unless the assignee's Copilot access has been canceled during the current billing cycle. If the seat has been cancelled, this corresponds to the start of the organization's next billing cycle.
    #[serde(rename = "pending_cancellation_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pending_cancellation_date: Option<Option<String>>,
    /// Timestamp of user's last GitHub Copilot activity, in ISO 8601 format.
    #[serde(rename = "last_activity_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_activity_at: Option<Option<String>>,
    /// Last editor that was used by the user for a GitHub Copilot completion.
    #[serde(rename = "last_activity_editor", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_activity_editor: Option<Option<String>>,
    /// Timestamp of when the assignee was last granted access to GitHub Copilot, in ISO 8601 format.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Timestamp of when the assignee's GitHub Copilot access was last updated, in ISO 8601 format.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl CopilotSeatDetails {
    /// Information about a Copilot Business seat assignment for a user, team, or organization.
    pub fn new(assignee: models::CopilotSeatDetailsAssignee, created_at: String) -> CopilotSeatDetails {
        CopilotSeatDetails {
            assignee: Box::new(assignee),
            assigning_team: None,
            pending_cancellation_date: None,
            last_activity_at: None,
            last_activity_editor: None,
            created_at,
            updated_at: None,
        }
    }
}

