/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CopilotListCopilotSeats200Response {
    /// Total number of Copilot seats for the organization currently being billed.
    #[serde(rename = "total_seats", skip_serializing_if = "Option::is_none")]
    pub total_seats: Option<i32>,
    #[serde(rename = "seats", skip_serializing_if = "Option::is_none")]
    pub seats: Option<Vec<models::CopilotSeatDetails>>,
}

impl CopilotListCopilotSeats200Response {
    pub fn new() -> CopilotListCopilotSeats200Response {
        CopilotListCopilotSeats200Response {
            total_seats: None,
            seats: None,
        }
    }
}

