/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CopilotAddCopilotSeatsForTeams201Response : The total number of seat assignments created.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CopilotAddCopilotSeatsForTeams201Response {
    #[serde(rename = "seats_created")]
    pub seats_created: i32,
}

impl CopilotAddCopilotSeatsForTeams201Response {
    /// The total number of seat assignments created.
    pub fn new(seats_created: i32) -> CopilotAddCopilotSeatsForTeams201Response {
        CopilotAddCopilotSeatsForTeams201Response {
            seats_created,
        }
    }
}

