/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CopilotSeatDetailsAssigningTeam : The team that granted access to GitHub Copilot to the assignee. This will be null if the user was assigned a seat individually.
/// The team that granted access to GitHub Copilot to the assignee. This will be null if the user was assigned a seat individually.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CopilotSeatDetailsAssigningTeam {
    Team(Box<models::Team>),
}

impl Default for CopilotSeatDetailsAssigningTeam {
    fn default() -> Self {
        Self::Team(Default::default())
    }
}

