/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CopilotAddCopilotSeatsForTeamsRequest {
    /// List of team names within the organization to which to grant access to GitHub Copilot.
    #[serde(rename = "selected_teams")]
    pub selected_teams: Vec<String>,
}

impl CopilotAddCopilotSeatsForTeamsRequest {
    pub fn new(selected_teams: Vec<String>) -> CopilotAddCopilotSeatsForTeamsRequest {
        CopilotAddCopilotSeatsForTeamsRequest {
            selected_teams,
        }
    }
}

