/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DependabotAlertSecurityAdvisoryCvss : Details for the advisory pertaining to the Common Vulnerability Scoring System.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DependabotAlertSecurityAdvisoryCvss {
    /// The overall CVSS score of the advisory.
    #[serde(rename = "score")]
    pub score: f64,
    /// The full CVSS vector string for the advisory.
    #[serde(rename = "vector_string", deserialize_with = "Option::deserialize")]
    pub vector_string: Option<String>,
}

impl DependabotAlertSecurityAdvisoryCvss {
    /// Details for the advisory pertaining to the Common Vulnerability Scoring System.
    pub fn new(score: f64, vector_string: Option<String>) -> DependabotAlertSecurityAdvisoryCvss {
        DependabotAlertSecurityAdvisoryCvss {
            score,
            vector_string,
        }
    }
}

