/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DependabotPublicKey : The public key used for setting Dependabot Secrets.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DependabotPublicKey {
    /// The identifier for the key.
    #[serde(rename = "key_id")]
    pub key_id: String,
    /// The Base64 encoded public key.
    #[serde(rename = "key")]
    pub key: String,
}

impl DependabotPublicKey {
    /// The public key used for setting Dependabot Secrets.
    pub fn new(key_id: String, key: String) -> DependabotPublicKey {
        DependabotPublicKey {
            key_id,
            key,
        }
    }
}

