/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DependabotAlertPackage : Details for the vulnerable package.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DependabotAlertPackage {
    /// The package's language or package management ecosystem.
    #[serde(rename = "ecosystem")]
    pub ecosystem: String,
    /// The unique package name within its ecosystem.
    #[serde(rename = "name")]
    pub name: String,
}

impl DependabotAlertPackage {
    /// Details for the vulnerable package.
    pub fn new(ecosystem: String, name: String) -> DependabotAlertPackage {
        DependabotAlertPackage {
            ecosystem,
            name,
        }
    }
}

