/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DependencyGraphSpdxSbom : A schema for the SPDX JSON format returned by the Dependency Graph.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DependencyGraphSpdxSbom {
    #[serde(rename = "sbom")]
    pub sbom: Box<models::DependencyGraphSpdxSbomSbom>,
}

impl DependencyGraphSpdxSbom {
    /// A schema for the SPDX JSON format returned by the Dependency Graph.
    pub fn new(sbom: models::DependencyGraphSpdxSbomSbom) -> DependencyGraphSpdxSbom {
        DependencyGraphSpdxSbom {
            sbom: Box::new(sbom),
        }
    }
}

