/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DependencyGraphSpdxSbomSbomPackagesInnerExternalRefsInner {
    /// The category of reference to an external resource this reference refers to.
    #[serde(rename = "referenceCategory")]
    pub reference_category: String,
    /// A locator for the particular external resource this reference refers to.
    #[serde(rename = "referenceLocator")]
    pub reference_locator: String,
    /// The category of reference to an external resource this reference refers to.
    #[serde(rename = "referenceType")]
    pub reference_type: String,
}

impl DependencyGraphSpdxSbomSbomPackagesInnerExternalRefsInner {
    pub fn new(reference_category: String, reference_locator: String, reference_type: String) -> DependencyGraphSpdxSbomSbomPackagesInnerExternalRefsInner {
        DependencyGraphSpdxSbomSbomPackagesInnerExternalRefsInner {
            reference_category,
            reference_locator,
            reference_type,
        }
    }
}

