/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnvironmentProtectionRulesInnerAnyOf2 {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "node_id")]
    pub node_id: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl EnvironmentProtectionRulesInnerAnyOf2 {
    pub fn new(id: i32, node_id: String, r#type: String) -> EnvironmentProtectionRulesInnerAnyOf2 {
        EnvironmentProtectionRulesInnerAnyOf2 {
            id,
            node_id,
            r#type,
        }
    }
}

