/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilePathRestrictionParameters {
    /// The file paths that are restricted from being pushed to the commit graph.
    #[serde(rename = "restricted_file_paths")]
    pub restricted_file_paths: Vec<String>,
}

impl FilePathRestrictionParameters {
    pub fn new(restricted_file_paths: Vec<String>) -> FilePathRestrictionParameters {
        FilePathRestrictionParameters {
            restricted_file_paths,
        }
    }
}

