/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GistHistoryChangeStatus {
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    #[serde(rename = "additions", skip_serializing_if = "Option::is_none")]
    pub additions: Option<i32>,
    #[serde(rename = "deletions", skip_serializing_if = "Option::is_none")]
    pub deletions: Option<i32>,
}

impl GistHistoryChangeStatus {
    pub fn new() -> GistHistoryChangeStatus {
        GistHistoryChangeStatus {
            total: None,
            additions: None,
            deletions: None,
        }
    }
}

