/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GistsGet403ResponseBlock {
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "html_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub html_url: Option<Option<String>>,
}

impl GistsGet403ResponseBlock {
    pub fn new() -> GistsGet403ResponseBlock {
        GistsGet403ResponseBlock {
            reason: None,
            created_at: None,
            html_url: None,
        }
    }
}

