/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GistsCreateRequest {
    /// Description of the gist
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Names and content for the files that make up the gist
    #[serde(rename = "files")]
    pub files: std::collections::HashMap<String, models::GistsCreateRequestFilesValue>,
    #[serde(rename = "public", skip_serializing_if = "Option::is_none")]
    pub public: Option<Box<models::GistsCreateRequestPublic>>,
}

impl GistsCreateRequest {
    pub fn new(files: std::collections::HashMap<String, models::GistsCreateRequestFilesValue>) -> GistsCreateRequest {
        GistsCreateRequest {
            description: None,
            files,
            public: None,
        }
    }
}

