/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitRefObject {
    #[serde(rename = "type")]
    pub r#type: String,
    /// SHA for the reference
    #[serde(rename = "sha")]
    pub sha: String,
    #[serde(rename = "url")]
    pub url: String,
}

impl GitRefObject {
    pub fn new(r#type: String, sha: String, url: String) -> GitRefObject {
        GitRefObject {
            r#type,
            sha,
            url,
        }
    }
}

