/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitCreateRefRequest {
    /// The name of the fully qualified reference (ie: `refs/heads/master`). If it doesn't start with 'refs' and have at least two slashes, it will be rejected.
    #[serde(rename = "ref")]
    pub r#ref: String,
    /// The SHA1 value for this reference.
    #[serde(rename = "sha")]
    pub sha: String,
}

impl GitCreateRefRequest {
    pub fn new(r#ref: String, sha: String) -> GitCreateRefRequest {
        GitCreateRefRequest {
            r#ref,
            sha,
        }
    }
}

