/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GlobalAdvisoryCvss {
    /// The CVSS vector.
    #[serde(rename = "vector_string", deserialize_with = "Option::deserialize")]
    pub vector_string: Option<String>,
    /// The CVSS score.
    #[serde(rename = "score", deserialize_with = "Option::deserialize")]
    pub score: Option<f64>,
}

impl GlobalAdvisoryCvss {
    pub fn new(vector_string: Option<String>, score: Option<f64>) -> GlobalAdvisoryCvss {
        GlobalAdvisoryCvss {
            vector_string,
            score,
        }
    }
}

