/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GlobalAdvisoryCreditsInner {
    #[serde(rename = "user")]
    pub user: Box<models::SimpleUser>,
    #[serde(rename = "type")]
    pub r#type: models::SecurityAdvisoryCreditTypes,
}

impl GlobalAdvisoryCreditsInner {
    pub fn new(user: models::SimpleUser, r#type: models::SecurityAdvisoryCreditTypes) -> GlobalAdvisoryCreditsInner {
        GlobalAdvisoryCreditsInner {
            user: Box::new(user),
            r#type,
        }
    }
}

