/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InteractionGroup : The type of GitHub user that can comment, open issues, or create pull requests while the interaction limit is in effect.
/// The type of GitHub user that can comment, open issues, or create pull requests while the interaction limit is in effect.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InteractionGroup {
    #[serde(rename = "existing_users")]
    ExistingUsers,
    #[serde(rename = "contributors_only")]
    ContributorsOnly,
    #[serde(rename = "collaborators_only")]
    CollaboratorsOnly,

}

impl std::fmt::Display for InteractionGroup {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ExistingUsers => write!(f, "existing_users"),
            Self::ContributorsOnly => write!(f, "contributors_only"),
            Self::CollaboratorsOnly => write!(f, "collaborators_only"),
        }
    }
}

impl Default for InteractionGroup {
    fn default() -> InteractionGroup {
        Self::ExistingUsers
    }
}

