/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssuesRemoveAssigneesRequest {
    /// Usernames of assignees to remove from an issue. _NOTE: Only users with push access can remove assignees from an issue. Assignees are silently ignored otherwise._
    #[serde(rename = "assignees")]
    pub assignees: Vec<String>,
}

impl IssuesRemoveAssigneesRequest {
    pub fn new(assignees: Vec<String>) -> IssuesRemoveAssigneesRequest {
        IssuesRemoveAssigneesRequest {
            assignees,
        }
    }
}

