/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssuesSetLabelsRequestOneOf1 {
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<models::IssuesSetLabelsRequestOneOf1LabelsInner>>,
}

impl IssuesSetLabelsRequestOneOf1 {
    pub fn new() -> IssuesSetLabelsRequestOneOf1 {
        IssuesSetLabelsRequestOneOf1 {
            labels: None,
        }
    }
}

