/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IssueEventLabel : Issue Event Label
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueEventLabel {
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    #[serde(rename = "color", deserialize_with = "Option::deserialize")]
    pub color: Option<String>,
}

impl IssueEventLabel {
    /// Issue Event Label
    pub fn new(name: Option<String>, color: Option<String>) -> IssueEventLabel {
        IssueEventLabel {
            name,
            color,
        }
    }
}

