/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MaxFileSize : Note: max_file_size is in beta and subject to change.  Prevent commits that exceed a specified file size limit from being pushed to the commit.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MaxFileSize {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Box<models::MaxFileSizeParameters>>,
}

impl MaxFileSize {
    /// Note: max_file_size is in beta and subject to change.  Prevent commits that exceed a specified file size limit from being pushed to the commit.
    pub fn new(r#type: Type) -> MaxFileSize {
        MaxFileSize {
            r#type,
            parameters: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "max_file_size")]
    MaxFileSize,
}

impl Default for Type {
    fn default() -> Type {
        Self::MaxFileSize
    }
}

