/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MaxFilePathLengthParameters {
    /// The maximum amount of characters allowed in file paths
    #[serde(rename = "max_file_path_length")]
    pub max_file_path_length: i32,
}

impl MaxFilePathLengthParameters {
    pub fn new(max_file_path_length: i32) -> MaxFilePathLengthParameters {
        MaxFilePathLengthParameters {
            max_file_path_length,
        }
    }
}

