/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NullableSimpleCommitCommitter : Information about the Git committer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NullableSimpleCommitCommitter {
    /// Name of the commit's committer
    #[serde(rename = "name")]
    pub name: String,
    /// Git email address of the commit's committer
    #[serde(rename = "email")]
    pub email: String,
}

impl NullableSimpleCommitCommitter {
    /// Information about the Git committer
    pub fn new(name: String, email: String) -> NullableSimpleCommitCommitter {
        NullableSimpleCommitCommitter {
            name,
            email,
        }
    }
}

