/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OidcCustomSub : Actions OIDC Subject customization
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OidcCustomSub {
    /// Array of unique strings. Each claim key can only contain alphanumeric characters and underscores.
    #[serde(rename = "include_claim_keys")]
    pub include_claim_keys: Vec<String>,
}

impl OidcCustomSub {
    /// Actions OIDC Subject customization
    pub fn new(include_claim_keys: Vec<String>) -> OidcCustomSub {
        OidcCustomSub {
            include_claim_keys,
        }
    }
}

