/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrganizationFineGrainedPermission : A fine-grained permission that protects organization resources.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationFineGrainedPermission {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
}

impl OrganizationFineGrainedPermission {
    /// A fine-grained permission that protects organization resources.
    pub fn new(name: String, description: String) -> OrganizationFineGrainedPermission {
        OrganizationFineGrainedPermission {
            name,
            description,
        }
    }
}

