/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrgsPatchCustomOrganizationRoleRequest {
    /// The name of the custom role.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// A short description about the intended usage of this role or what permissions it grants.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// A list of additional permissions included in this role.
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Vec<String>>,
}

impl OrgsPatchCustomOrganizationRoleRequest {
    pub fn new() -> OrgsPatchCustomOrganizationRoleRequest {
        OrgsPatchCustomOrganizationRoleRequest {
            name: None,
            description: None,
            permissions: None,
        }
    }
}

