/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrgsUpdatePatAccessRequest {
    /// Action to apply to the fine-grained personal access token.
    #[serde(rename = "action")]
    pub action: Action,
}

impl OrgsUpdatePatAccessRequest {
    pub fn new(action: Action) -> OrgsUpdatePatAccessRequest {
        OrgsUpdatePatAccessRequest {
            action,
        }
    }
}
/// Action to apply to the fine-grained personal access token.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "revoke")]
    Revoke,
}

impl Default for Action {
    fn default() -> Action {
        Self::Revoke
    }
}

