/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrgsCreateCustomOrganizationRoleRequest {
    /// The name of the custom role.
    #[serde(rename = "name")]
    pub name: String,
    /// A short description about the intended usage of this role or what permissions it grants.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// A list of additional permissions included in this role.
    #[serde(rename = "permissions")]
    pub permissions: Vec<String>,
}

impl OrgsCreateCustomOrganizationRoleRequest {
    pub fn new(name: String, permissions: Vec<String>) -> OrgsCreateCustomOrganizationRoleRequest {
        OrgsCreateCustomOrganizationRoleRequest {
            name,
            description: None,
            permissions,
        }
    }
}

