/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PagesSourceHash {
    #[serde(rename = "branch")]
    pub branch: String,
    #[serde(rename = "path")]
    pub path: String,
}

impl PagesSourceHash {
    pub fn new(branch: String, path: String) -> PagesSourceHash {
        PagesSourceHash {
            branch,
            path,
        }
    }
}

