/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PageDeployment : The GitHub Pages deployment status.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PageDeployment {
    #[serde(rename = "id")]
    pub id: Box<models::PageDeploymentId>,
    /// The URI to monitor GitHub Pages deployment status.
    #[serde(rename = "status_url")]
    pub status_url: String,
    /// The URI to the deployed GitHub Pages.
    #[serde(rename = "page_url")]
    pub page_url: String,
    /// The URI to the deployed GitHub Pages preview.
    #[serde(rename = "preview_url", skip_serializing_if = "Option::is_none")]
    pub preview_url: Option<String>,
}

impl PageDeployment {
    /// The GitHub Pages deployment status.
    pub fn new(id: models::PageDeploymentId, status_url: String, page_url: String) -> PageDeployment {
        PageDeployment {
            id: Box::new(id),
            status_url,
            page_url,
            preview_url: None,
        }
    }
}

