/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParticipationStats {
    #[serde(rename = "all")]
    pub all: Vec<i32>,
    #[serde(rename = "owner")]
    pub owner: Vec<i32>,
}

impl ParticipationStats {
    pub fn new(all: Vec<i32>, owner: Vec<i32>) -> ParticipationStats {
        ParticipationStats {
            all,
            owner,
        }
    }
}

