/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PendingDeploymentReviewersInner {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::DeploymentReviewerType>,
    #[serde(rename = "reviewer", skip_serializing_if = "Option::is_none")]
    pub reviewer: Option<Box<models::PendingDeploymentReviewersInnerReviewer>>,
}

impl PendingDeploymentReviewersInner {
    pub fn new() -> PendingDeploymentReviewersInner {
        PendingDeploymentReviewersInner {
            r#type: None,
            reviewer: None,
        }
    }
}

