/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectsMoveColumnRequest {
    /// The position of the column in a project. Can be one of: `first`, `last`, or `after:<column_id>` to place after the specified column.
    #[serde(rename = "position")]
    pub position: String,
}

impl ProjectsMoveColumnRequest {
    pub fn new(position: String) -> ProjectsMoveColumnRequest {
        ProjectsMoveColumnRequest {
            position,
        }
    }
}

