/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectsCreateCardRequestOneOf1 {
    /// The unique identifier of the content associated with the card
    #[serde(rename = "content_id")]
    pub content_id: i32,
    /// The piece of content associated with the card
    #[serde(rename = "content_type")]
    pub content_type: String,
}

impl ProjectsCreateCardRequestOneOf1 {
    pub fn new(content_id: i32, content_type: String) -> ProjectsCreateCardRequestOneOf1 {
        ProjectsCreateCardRequestOneOf1 {
            content_id,
            content_type,
        }
    }
}

