/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicUserPlan {
    #[serde(rename = "collaborators")]
    pub collaborators: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "space")]
    pub space: i32,
    #[serde(rename = "private_repos")]
    pub private_repos: i32,
}

impl PublicUserPlan {
    pub fn new(collaborators: i32, name: String, space: i32, private_repos: i32) -> PublicUserPlan {
        PublicUserPlan {
            collaborators,
            name,
            space,
            private_repos,
        }
    }
}

