/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PullsRequestReviewersRequest {
    /// An array of user `login`s that will be requested.
    #[serde(rename = "reviewers", skip_serializing_if = "Option::is_none")]
    pub reviewers: Option<Vec<String>>,
    /// An array of team `slug`s that will be requested.
    #[serde(rename = "team_reviewers", skip_serializing_if = "Option::is_none")]
    pub team_reviewers: Option<Vec<String>>,
}

impl PullsRequestReviewersRequest {
    pub fn new() -> PullsRequestReviewersRequest {
        PullsRequestReviewersRequest {
            reviewers: None,
            team_reviewers: None,
        }
    }
}

