/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PullsRemoveRequestedReviewersRequest {
    /// An array of user `login`s that will be removed.
    #[serde(rename = "reviewers")]
    pub reviewers: Vec<String>,
    /// An array of team `slug`s that will be removed.
    #[serde(rename = "team_reviewers", skip_serializing_if = "Option::is_none")]
    pub team_reviewers: Option<Vec<String>>,
}

impl PullsRemoveRequestedReviewersRequest {
    pub fn new(reviewers: Vec<String>) -> PullsRemoveRequestedReviewersRequest {
        PullsRemoveRequestedReviewersRequest {
            reviewers,
            team_reviewers: None,
        }
    }
}

