/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PullRequestMinimal {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "number")]
    pub number: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "head")]
    pub head: Box<models::PullRequestMinimalHead>,
    #[serde(rename = "base")]
    pub base: Box<models::PullRequestMinimalHead>,
}

impl PullRequestMinimal {
    pub fn new(id: i32, number: i32, url: String, head: models::PullRequestMinimalHead, base: models::PullRequestMinimalHead) -> PullRequestMinimal {
        PullRequestMinimal {
            id,
            number,
            url,
            head: Box::new(head),
            base: Box::new(base),
        }
    }
}

