/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReferencedWorkflow : A workflow referenced/reused by the initial caller workflow
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReferencedWorkflow {
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "sha")]
    pub sha: String,
    #[serde(rename = "ref", skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<String>,
}

impl ReferencedWorkflow {
    /// A workflow referenced/reused by the initial caller workflow
    pub fn new(path: String, sha: String) -> ReferencedWorkflow {
        ReferencedWorkflow {
            path,
            sha,
            r#ref: None,
        }
    }
}

