/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReposTransferRequest {
    /// The username or organization name the repository will be transferred to.
    #[serde(rename = "new_owner")]
    pub new_owner: String,
    /// The new name to be given to the repository.
    #[serde(rename = "new_name", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
    /// ID of the team or teams to add to the repository. Teams can only be added to organization-owned repositories.
    #[serde(rename = "team_ids", skip_serializing_if = "Option::is_none")]
    pub team_ids: Option<Vec<i32>>,
}

impl ReposTransferRequest {
    pub fn new(new_owner: String) -> ReposTransferRequest {
        ReposTransferRequest {
            new_owner,
            new_name: None,
            team_ids: None,
        }
    }
}

