/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReposReplaceAllTopicsRequest {
    /// An array of topics to add to the repository. Pass one or more topics to _replace_ the set of existing topics. Send an empty array (`[]`) to clear all topics from the repository. **Note:** Topic `names` cannot contain uppercase letters.
    #[serde(rename = "names")]
    pub names: Vec<String>,
}

impl ReposReplaceAllTopicsRequest {
    pub fn new(names: Vec<String>) -> ReposReplaceAllTopicsRequest {
        ReposReplaceAllTopicsRequest {
            names,
        }
    }
}

