/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReposUpdateRequestSecurityAndAnalysisAdvancedSecurity : Use the `status` property to enable or disable GitHub Advanced Security for this repository. For more information, see \"[About GitHub Advanced Security](/github/getting-started-with-github/learning-about-github/about-github-advanced-security).\"
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReposUpdateRequestSecurityAndAnalysisAdvancedSecurity {
    /// Can be `enabled` or `disabled`.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl ReposUpdateRequestSecurityAndAnalysisAdvancedSecurity {
    /// Use the `status` property to enable or disable GitHub Advanced Security for this repository. For more information, see \"[About GitHub Advanced Security](/github/getting-started-with-github/learning-about-github/about-github-advanced-security).\"
    pub fn new() -> ReposUpdateRequestSecurityAndAnalysisAdvancedSecurity {
        ReposUpdateRequestSecurityAndAnalysisAdvancedSecurity {
            status: None,
        }
    }
}

