/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReposCreateDeploymentProtectionRuleRequest {
    /// The ID of the custom app that will be enabled on the environment.
    #[serde(rename = "integration_id", skip_serializing_if = "Option::is_none")]
    pub integration_id: Option<i32>,
}

impl ReposCreateDeploymentProtectionRuleRequest {
    pub fn new() -> ReposCreateDeploymentProtectionRuleRequest {
        ReposCreateDeploymentProtectionRuleRequest {
            integration_id: None,
        }
    }
}

