/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RepositoryRulesetConditionsRepositoryPropertyTarget : Parameters for a repository property condition
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryRulesetConditionsRepositoryPropertyTarget {
    #[serde(rename = "repository_property")]
    pub repository_property: Box<models::RepositoryRulesetConditionsRepositoryPropertyTargetRepositoryProperty>,
}

impl RepositoryRulesetConditionsRepositoryPropertyTarget {
    /// Parameters for a repository property condition
    pub fn new(repository_property: models::RepositoryRulesetConditionsRepositoryPropertyTargetRepositoryProperty) -> RepositoryRulesetConditionsRepositoryPropertyTarget {
        RepositoryRulesetConditionsRepositoryPropertyTarget {
            repository_property: Box::new(repository_property),
        }
    }
}

