/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RepositoryRuleRequiredDeployments : Choose which environments must be successfully deployed to before refs can be pushed into a ref that matches this rule.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryRuleRequiredDeployments {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Box<models::RepositoryRuleRequiredDeploymentsParameters>>,
}

impl RepositoryRuleRequiredDeployments {
    /// Choose which environments must be successfully deployed to before refs can be pushed into a ref that matches this rule.
    pub fn new(r#type: Type) -> RepositoryRuleRequiredDeployments {
        RepositoryRuleRequiredDeployments {
            r#type,
            parameters: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "required_deployments")]
    RequiredDeployments,
}

impl Default for Type {
    fn default() -> Type {
        Self::RequiredDeployments
    }
}

