/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RepositoryRuleNonFastForward : Prevent users with push access from force pushing to refs.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryRuleNonFastForward {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl RepositoryRuleNonFastForward {
    /// Prevent users with push access from force pushing to refs.
    pub fn new(r#type: Type) -> RepositoryRuleNonFastForward {
        RepositoryRuleNonFastForward {
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "non_fast_forward")]
    NonFastForward,
}

impl Default for Type {
    fn default() -> Type {
        Self::NonFastForward
    }
}

