/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryRuleRequiredDeploymentsParameters {
    /// The environments that must be successfully deployed to before branches can be merged.
    #[serde(rename = "required_deployment_environments")]
    pub required_deployment_environments: Vec<String>,
}

impl RepositoryRuleRequiredDeploymentsParameters {
    pub fn new(required_deployment_environments: Vec<String>) -> RepositoryRuleRequiredDeploymentsParameters {
        RepositoryRuleRequiredDeploymentsParameters {
            required_deployment_environments,
        }
    }
}

