/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryRuleWorkflowsParameters {
    /// Workflows that must pass for this rule to pass.
    #[serde(rename = "workflows")]
    pub workflows: Vec<models::RepositoryRuleParamsWorkflowFileReference>,
}

impl RepositoryRuleWorkflowsParameters {
    pub fn new(workflows: Vec<models::RepositoryRuleParamsWorkflowFileReference>) -> RepositoryRuleWorkflowsParameters {
        RepositoryRuleWorkflowsParameters {
            workflows,
        }
    }
}

