/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReposListCustomDeploymentRuleIntegrations200Response {
    /// The total number of custom deployment protection rule integrations available for this environment.
    #[serde(rename = "total_count", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<i32>,
    #[serde(rename = "available_custom_deployment_protection_rule_integrations", skip_serializing_if = "Option::is_none")]
    pub available_custom_deployment_protection_rule_integrations: Option<Vec<models::CustomDeploymentRuleApp>>,
}

impl ReposListCustomDeploymentRuleIntegrations200Response {
    pub fn new() -> ReposListCustomDeploymentRuleIntegrations200Response {
        ReposListCustomDeploymentRuleIntegrations200Response {
            total_count: None,
            available_custom_deployment_protection_rule_integrations: None,
        }
    }
}

