/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReposDeleteFileRequestAuthor : object containing information about the author.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReposDeleteFileRequestAuthor {
    /// The name of the author (or committer) of the commit
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The email of the author (or committer) of the commit
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
}

impl ReposDeleteFileRequestAuthor {
    /// object containing information about the author.
    pub fn new() -> ReposDeleteFileRequestAuthor {
        ReposDeleteFileRequestAuthor {
            name: None,
            email: None,
        }
    }
}

