/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReposListDeploymentBranchPolicies200Response {
    /// The number of deployment branch policies for the environment.
    #[serde(rename = "total_count")]
    pub total_count: i32,
    #[serde(rename = "branch_policies")]
    pub branch_policies: Vec<models::DeploymentBranchPolicy>,
}

impl ReposListDeploymentBranchPolicies200Response {
    pub fn new(total_count: i32, branch_policies: Vec<models::DeploymentBranchPolicy>) -> ReposListDeploymentBranchPolicies200Response {
        ReposListDeploymentBranchPolicies200Response {
            total_count,
            branch_policies,
        }
    }
}

