/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryRuleUpdateParameters {
    /// Branch can pull changes from its upstream repository
    #[serde(rename = "update_allows_fetch_and_merge")]
    pub update_allows_fetch_and_merge: bool,
}

impl RepositoryRuleUpdateParameters {
    pub fn new(update_allows_fetch_and_merge: bool) -> RepositoryRuleUpdateParameters {
        RepositoryRuleUpdateParameters {
            update_allows_fetch_and_merge,
        }
    }
}

