/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RepositoryRuleRequiredSignatures : Commits pushed to matching refs must have verified signatures.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryRuleRequiredSignatures {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl RepositoryRuleRequiredSignatures {
    /// Commits pushed to matching refs must have verified signatures.
    pub fn new(r#type: Type) -> RepositoryRuleRequiredSignatures {
        RepositoryRuleRequiredSignatures {
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "required_signatures")]
    RequiredSignatures,
}

impl Default for Type {
    fn default() -> Type {
        Self::RequiredSignatures
    }
}

