/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReposCreateDeploymentRequestPayload {
    Object(std::collections::HashMap<String, serde_json::Value>),
    /// JSON payload with extra information about the deployment.
    String(String),
}

impl Default for ReposCreateDeploymentRequestPayload {
    fn default() -> Self {
        Self::Object(Default::default())
    }
}

