/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RepositoryRulesetConditionsRepositoryNameTarget : Parameters for a repository name condition
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryRulesetConditionsRepositoryNameTarget {
    #[serde(rename = "repository_name")]
    pub repository_name: Box<models::RepositoryRulesetConditionsRepositoryNameTargetRepositoryName>,
}

impl RepositoryRulesetConditionsRepositoryNameTarget {
    /// Parameters for a repository name condition
    pub fn new(repository_name: models::RepositoryRulesetConditionsRepositoryNameTargetRepositoryName) -> RepositoryRulesetConditionsRepositoryNameTarget {
        RepositoryRulesetConditionsRepositoryNameTarget {
            repository_name: Box::new(repository_name),
        }
    }
}

