/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RepositoryRulesetConditionsRepositoryPropertySpec : Parameters for a targeting a repository property
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryRulesetConditionsRepositoryPropertySpec {
    /// The name of the repository property to target
    #[serde(rename = "name")]
    pub name: String,
    /// The values to match for the repository property
    #[serde(rename = "property_values")]
    pub property_values: Vec<String>,
}

impl RepositoryRulesetConditionsRepositoryPropertySpec {
    /// Parameters for a targeting a repository property
    pub fn new(name: String, property_values: Vec<String>) -> RepositoryRulesetConditionsRepositoryPropertySpec {
        RepositoryRulesetConditionsRepositoryPropertySpec {
            name,
            property_values,
        }
    }
}

