/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReposCreateOrUpdateFileContentsRequestCommitter : The person that committed the file. Default: the authenticated user.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReposCreateOrUpdateFileContentsRequestCommitter {
    /// The name of the author or committer of the commit. You'll receive a `422` status code if `name` is omitted.
    #[serde(rename = "name")]
    pub name: String,
    /// The email of the author or committer of the commit. You'll receive a `422` status code if `email` is omitted.
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
}

impl ReposCreateOrUpdateFileContentsRequestCommitter {
    /// The person that committed the file. Default: the authenticated user.
    pub fn new(name: String, email: String) -> ReposCreateOrUpdateFileContentsRequestCommitter {
        ReposCreateOrUpdateFileContentsRequestCommitter {
            name,
            email,
            date: None,
        }
    }
}

