/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryRulesetConditionsRepositoryIdTargetRepositoryId {
    /// The repository IDs that the ruleset applies to. One of these IDs must match for the condition to pass.
    #[serde(rename = "repository_ids", skip_serializing_if = "Option::is_none")]
    pub repository_ids: Option<Vec<i32>>,
}

impl RepositoryRulesetConditionsRepositoryIdTargetRepositoryId {
    pub fn new() -> RepositoryRulesetConditionsRepositoryIdTargetRepositoryId {
        RepositoryRulesetConditionsRepositoryIdTargetRepositoryId {
            repository_ids: None,
        }
    }
}

