/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RepositoryRuleParamsRestrictedCommits : Restricted commit
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryRuleParamsRestrictedCommits {
    /// Full or abbreviated commit hash to reject
    #[serde(rename = "oid")]
    pub oid: String,
    /// Reason for restriction
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl RepositoryRuleParamsRestrictedCommits {
    /// Restricted commit
    pub fn new(oid: String) -> RepositoryRuleParamsRestrictedCommits {
        RepositoryRuleParamsRestrictedCommits {
            oid,
            reason: None,
        }
    }
}

