/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretScanningLocationIssueComment : Represents an 'issue_comment' secret scanning location type. This location type shows that a secret was detected in a comment on an issue.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretScanningLocationIssueComment {
    /// The API URL to get the issue comment where the secret was detected.
    #[serde(rename = "issue_comment_url")]
    pub issue_comment_url: String,
}

impl SecretScanningLocationIssueComment {
    /// Represents an 'issue_comment' secret scanning location type. This location type shows that a secret was detected in a comment on an issue.
    pub fn new(issue_comment_url: String) -> SecretScanningLocationIssueComment {
        SecretScanningLocationIssueComment {
            issue_comment_url,
        }
    }
}

