/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretScanningLocationDiscussionTitle : Represents a 'discussion_title' secret scanning location type. This location type shows that a secret was detected in the title of a discussion.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretScanningLocationDiscussionTitle {
    /// The URL to the discussion where the secret was detected.
    #[serde(rename = "discussion_title_url")]
    pub discussion_title_url: String,
}

impl SecretScanningLocationDiscussionTitle {
    /// Represents a 'discussion_title' secret scanning location type. This location type shows that a secret was detected in the title of a discussion.
    pub fn new(discussion_title_url: String) -> SecretScanningLocationDiscussionTitle {
        SecretScanningLocationDiscussionTitle {
            discussion_title_url,
        }
    }
}

