/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretScanningLocationDiscussionComment : Represents a 'discussion_comment' secret scanning location type. This location type shows that a secret was detected in a comment on a discussion.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretScanningLocationDiscussionComment {
    /// The API URL to get the discussion comment where the secret was detected.
    #[serde(rename = "discussion_comment_url")]
    pub discussion_comment_url: String,
}

impl SecretScanningLocationDiscussionComment {
    /// Represents a 'discussion_comment' secret scanning location type. This location type shows that a secret was detected in a comment on a discussion.
    pub fn new(discussion_comment_url: String) -> SecretScanningLocationDiscussionComment {
        SecretScanningLocationDiscussionComment {
            discussion_comment_url,
        }
    }
}

