/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecretScanningLocationDiscussionBody : Represents a 'discussion_body' secret scanning location type. This location type shows that a secret was detected in the body of a discussion.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretScanningLocationDiscussionBody {
    /// The URL to the discussion where the secret was detected.
    #[serde(rename = "discussion_body_url")]
    pub discussion_body_url: String,
}

impl SecretScanningLocationDiscussionBody {
    /// Represents a 'discussion_body' secret scanning location type. This location type shows that a secret was detected in the body of a discussion.
    pub fn new(discussion_body_url: String) -> SecretScanningLocationDiscussionBody {
        SecretScanningLocationDiscussionBody {
            discussion_body_url,
        }
    }
}

