/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecurityAndAnalysis {
    #[serde(rename = "advanced_security", skip_serializing_if = "Option::is_none")]
    pub advanced_security: Option<Box<models::SecurityAndAnalysisAdvancedSecurity>>,
    #[serde(rename = "dependabot_security_updates", skip_serializing_if = "Option::is_none")]
    pub dependabot_security_updates: Option<Box<models::SecurityAndAnalysisDependabotSecurityUpdates>>,
    #[serde(rename = "secret_scanning", skip_serializing_if = "Option::is_none")]
    pub secret_scanning: Option<Box<models::SecurityAndAnalysisAdvancedSecurity>>,
    #[serde(rename = "secret_scanning_push_protection", skip_serializing_if = "Option::is_none")]
    pub secret_scanning_push_protection: Option<Box<models::SecurityAndAnalysisAdvancedSecurity>>,
}

impl SecurityAndAnalysis {
    pub fn new() -> SecurityAndAnalysis {
        SecurityAndAnalysis {
            advanced_security: None,
            dependabot_security_updates: None,
            secret_scanning: None,
            secret_scanning_push_protection: None,
        }
    }
}

