/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SimpleInstallation : The GitHub App installation. Webhook payloads contain the `installation` property when the event is configured for and sent to a GitHub App. For more information, see \"[Using webhooks with GitHub Apps](https://docs.github.com/apps/creating-github-apps/registering-a-github-app/using-webhooks-with-github-apps).\"
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimpleInstallation {
    /// The ID of the installation.
    #[serde(rename = "id")]
    pub id: i32,
    /// The global node ID of the installation.
    #[serde(rename = "node_id")]
    pub node_id: String,
}

impl SimpleInstallation {
    /// The GitHub App installation. Webhook payloads contain the `installation` property when the event is configured for and sent to a GitHub App. For more information, see \"[Using webhooks with GitHub Apps](https://docs.github.com/apps/creating-github-apps/registering-a-github-app/using-webhooks-with-github-apps).\"
    pub fn new(id: i32, node_id: String) -> SimpleInstallation {
        SimpleInstallation {
            id,
            node_id,
        }
    }
}

