/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SimpleClassroomOrganization : A GitHub organization.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimpleClassroomOrganization {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "login")]
    pub login: String,
    #[serde(rename = "node_id")]
    pub node_id: String,
    #[serde(rename = "html_url")]
    pub html_url: String,
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    #[serde(rename = "avatar_url")]
    pub avatar_url: String,
}

impl SimpleClassroomOrganization {
    /// A GitHub organization.
    pub fn new(id: i32, login: String, node_id: String, html_url: String, name: Option<String>, avatar_url: String) -> SimpleClassroomOrganization {
        SimpleClassroomOrganization {
            id,
            login,
            node_id,
            html_url,
            name,
            avatar_url,
        }
    }
}

