/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Stargazer : Stargazer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Stargazer {
    #[serde(rename = "starred_at")]
    pub starred_at: String,
    #[serde(rename = "user", deserialize_with = "Option::deserialize")]
    pub user: Option<Box<models::NullableSimpleUser>>,
}

impl Stargazer {
    /// Stargazer
    pub fn new(starred_at: String, user: Option<models::NullableSimpleUser>) -> Stargazer {
        Stargazer {
            starred_at,
            user: if let Some(x) = user {Some(Box::new(x))} else {None},
        }
    }
}

