/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusCheckPolicyChecksInner {
    #[serde(rename = "context")]
    pub context: String,
    #[serde(rename = "app_id", deserialize_with = "Option::deserialize")]
    pub app_id: Option<i32>,
}

impl StatusCheckPolicyChecksInner {
    pub fn new(context: String, app_id: Option<i32>) -> StatusCheckPolicyChecksInner {
        StatusCheckPolicyChecksInner {
            context,
            app_id,
        }
    }
}

