/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamsAddOrUpdateMembershipForUserInOrgRequest {
    /// The role that this user should have in the team.
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<Role>,
}

impl TeamsAddOrUpdateMembershipForUserInOrgRequest {
    pub fn new() -> TeamsAddOrUpdateMembershipForUserInOrgRequest {
        TeamsAddOrUpdateMembershipForUserInOrgRequest {
            role: None,
        }
    }
}
/// The role that this user should have in the team.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "member")]
    Member,
    #[serde(rename = "maintainer")]
    Maintainer,
}

impl Default for Role {
    fn default() -> Role {
        Self::Member
    }
}

