/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamsCreateDiscussionInOrgRequest {
    /// The discussion post's title.
    #[serde(rename = "title")]
    pub title: String,
    /// The discussion post's body text.
    #[serde(rename = "body")]
    pub body: String,
    /// Private posts are only visible to team members, organization owners, and team maintainers. Public posts are visible to all members of the organization. Set to `true` to create a private post.
    #[serde(rename = "private", skip_serializing_if = "Option::is_none")]
    pub private: Option<bool>,
}

impl TeamsCreateDiscussionInOrgRequest {
    pub fn new(title: String, body: String) -> TeamsCreateDiscussionInOrgRequest {
        TeamsCreateDiscussionInOrgRequest {
            title,
            body,
            private: None,
        }
    }
}

