/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamProjectPermissions {
    #[serde(rename = "read")]
    pub read: bool,
    #[serde(rename = "write")]
    pub write: bool,
    #[serde(rename = "admin")]
    pub admin: bool,
}

impl TeamProjectPermissions {
    pub fn new(read: bool, write: bool, admin: bool) -> TeamProjectPermissions {
        TeamProjectPermissions {
            read,
            write,
            admin,
        }
    }
}

