/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Traffic {
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "uniques")]
    pub uniques: i32,
    #[serde(rename = "count")]
    pub count: i32,
}

impl Traffic {
    pub fn new(timestamp: String, uniques: i32, count: i32) -> Traffic {
        Traffic {
            timestamp,
            uniques,
            count,
        }
    }
}

