/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsersAddEmailForAuthenticatedUserRequestOneOf {
    /// Adds one or more email addresses to your GitHub account. Must contain at least one email address. **Note:** Alternatively, you can pass a single email address or an `array` of emails addresses directly, but we recommend that you pass an object using the `emails` key.
    #[serde(rename = "emails")]
    pub emails: Vec<String>,
}

impl UsersAddEmailForAuthenticatedUserRequestOneOf {
    pub fn new(emails: Vec<String>) -> UsersAddEmailForAuthenticatedUserRequestOneOf {
        UsersAddEmailForAuthenticatedUserRequestOneOf {
            emails,
        }
    }
}

