/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsersCreatePublicSshKeyForAuthenticatedUserRequest {
    /// A descriptive name for the new key.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// The public SSH key to add to your GitHub account.
    #[serde(rename = "key")]
    pub key: String,
}

impl UsersCreatePublicSshKeyForAuthenticatedUserRequest {
    pub fn new(key: String) -> UsersCreatePublicSshKeyForAuthenticatedUserRequest {
        UsersCreatePublicSshKeyForAuthenticatedUserRequest {
            title: None,
            key,
        }
    }
}

