/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsersAddSocialAccountForAuthenticatedUserRequest {
    /// Full URLs for the social media profiles to add.
    #[serde(rename = "account_urls")]
    pub account_urls: Vec<String>,
}

impl UsersAddSocialAccountForAuthenticatedUserRequest {
    pub fn new(account_urls: Vec<String>) -> UsersAddSocialAccountForAuthenticatedUserRequest {
        UsersAddSocialAccountForAuthenticatedUserRequest {
            account_urls,
        }
    }
}

