/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ViewTraffic : View Traffic
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ViewTraffic {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "uniques")]
    pub uniques: i32,
    #[serde(rename = "views")]
    pub views: Vec<models::Traffic>,
}

impl ViewTraffic {
    /// View Traffic
    pub fn new(count: i32, uniques: i32, views: Vec<models::Traffic>) -> ViewTraffic {
        ViewTraffic {
            count,
            uniques,
            views,
        }
    }
}

