/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookRepositoryRulesetEditedChangesConditionsUpdatedInner {
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<Box<models::RepositoryRulesetConditions>>,
    #[serde(rename = "changes", skip_serializing_if = "Option::is_none")]
    pub changes: Option<Box<models::WebhookRepositoryRulesetEditedChangesConditionsUpdatedInnerChanges>>,
}

impl WebhookRepositoryRulesetEditedChangesConditionsUpdatedInner {
    pub fn new() -> WebhookRepositoryRulesetEditedChangesConditionsUpdatedInner {
        WebhookRepositoryRulesetEditedChangesConditionsUpdatedInner {
            condition: None,
            changes: None,
        }
    }
}

