/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookProjectsV2ItemConvertedChanges {
    #[serde(rename = "content_type", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<Box<models::WebhookProjectsV2ItemConvertedChangesContentType>>,
}

impl WebhookProjectsV2ItemConvertedChanges {
    pub fn new() -> WebhookProjectsV2ItemConvertedChanges {
        WebhookProjectsV2ItemConvertedChanges {
            content_type: None,
        }
    }
}

