/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookProjectsV2ProjectEditedChangesPublic {
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<bool>,
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<bool>,
}

impl WebhookProjectsV2ProjectEditedChangesPublic {
    pub fn new() -> WebhookProjectsV2ProjectEditedChangesPublic {
        WebhookProjectsV2ProjectEditedChangesPublic {
            from: None,
            to: None,
        }
    }
}

