/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookLabelEditedChanges : The changes to the label if the action was `edited`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookLabelEditedChanges {
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<Box<models::WebhookLabelEditedChangesColor>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<Box<models::WebhookLabelEditedChangesDescription>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Box<models::WebhookLabelEditedChangesName>>,
}

impl WebhookLabelEditedChanges {
    /// The changes to the label if the action was `edited`.
    pub fn new() -> WebhookLabelEditedChanges {
        WebhookLabelEditedChanges {
            color: None,
            description: None,
            name: None,
        }
    }
}

