/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookPullRequestReviewThreadResolvedThread {
    #[serde(rename = "comments")]
    pub comments: Vec<models::PullRequestReviewComment1>,
    #[serde(rename = "node_id")]
    pub node_id: String,
}

impl WebhookPullRequestReviewThreadResolvedThread {
    pub fn new(comments: Vec<models::PullRequestReviewComment1>, node_id: String) -> WebhookPullRequestReviewThreadResolvedThread {
        WebhookPullRequestReviewThreadResolvedThread {
            comments,
            node_id,
        }
    }
}

