/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookMemberAddedChanges {
    #[serde(rename = "permission", skip_serializing_if = "Option::is_none")]
    pub permission: Option<Box<models::WebhookMemberAddedChangesPermission>>,
    #[serde(rename = "role_name", skip_serializing_if = "Option::is_none")]
    pub role_name: Option<Box<models::WebhookMemberAddedChangesRoleName>>,
}

impl WebhookMemberAddedChanges {
    pub fn new() -> WebhookMemberAddedChanges {
        WebhookMemberAddedChanges {
            permission: None,
            role_name: None,
        }
    }
}

