/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookPullRequestEditedChangesBase {
    #[serde(rename = "ref")]
    pub r#ref: Box<models::WebhookDiscussionCommentEditedChangesBody>,
    #[serde(rename = "sha")]
    pub sha: Box<models::WebhookDiscussionCommentEditedChangesBody>,
}

impl WebhookPullRequestEditedChangesBase {
    pub fn new(r#ref: models::WebhookDiscussionCommentEditedChangesBody, sha: models::WebhookDiscussionCommentEditedChangesBody) -> WebhookPullRequestEditedChangesBase {
        WebhookPullRequestEditedChangesBase {
            r#ref: Box::new(r#ref),
            sha: Box::new(sha),
        }
    }
}

