/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookSecurityAndAnalysisChangesFrom {
    #[serde(rename = "security_and_analysis", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub security_and_analysis: Option<Option<Box<models::SecurityAndAnalysis>>>,
}

impl WebhookSecurityAndAnalysisChangesFrom {
    pub fn new() -> WebhookSecurityAndAnalysisChangesFrom {
        WebhookSecurityAndAnalysisChangesFrom {
            security_and_analysis: None,
        }
    }
}

