/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookDiscussionCommentEditedChanges {
    #[serde(rename = "body")]
    pub body: Box<models::WebhookDiscussionCommentEditedChangesBody>,
}

impl WebhookDiscussionCommentEditedChanges {
    pub fn new(body: models::WebhookDiscussionCommentEditedChangesBody) -> WebhookDiscussionCommentEditedChanges {
        WebhookDiscussionCommentEditedChanges {
            body: Box::new(body),
        }
    }
}

