/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookRepositoryEditedChanges {
    #[serde(rename = "default_branch", skip_serializing_if = "Option::is_none")]
    pub default_branch: Option<Box<models::WebhookDiscussionCommentEditedChangesBody>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<Box<models::WebhookProjectCardEditedChangesNote>>,
    #[serde(rename = "homepage", skip_serializing_if = "Option::is_none")]
    pub homepage: Option<Box<models::WebhookProjectCardEditedChangesNote>>,
    #[serde(rename = "topics", skip_serializing_if = "Option::is_none")]
    pub topics: Option<Box<models::WebhookRepositoryEditedChangesTopics>>,
}

impl WebhookRepositoryEditedChanges {
    pub fn new() -> WebhookRepositoryEditedChanges {
        WebhookRepositoryEditedChanges {
            default_branch: None,
            description: None,
            homepage: None,
            topics: None,
        }
    }
}

