/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhooksSecurityAdvisoryCvss {
    #[serde(rename = "score")]
    pub score: f64,
    #[serde(rename = "vector_string", deserialize_with = "Option::deserialize")]
    pub vector_string: Option<String>,
}

impl WebhooksSecurityAdvisoryCvss {
    pub fn new(score: f64, vector_string: Option<String>) -> WebhooksSecurityAdvisoryCvss {
        WebhooksSecurityAdvisoryCvss {
            score,
            vector_string,
        }
    }
}

