/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookMilestoneEditedChanges : The changes to the milestone if the action was `edited`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookMilestoneEditedChanges {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<Box<models::WebhookLabelEditedChangesDescription>>,
    #[serde(rename = "due_on", skip_serializing_if = "Option::is_none")]
    pub due_on: Option<Box<models::WebhookMilestoneEditedChangesDueOn>>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<Box<models::WebhookMilestoneEditedChangesTitle>>,
}

impl WebhookMilestoneEditedChanges {
    /// The changes to the milestone if the action was `edited`.
    pub fn new() -> WebhookMilestoneEditedChanges {
        WebhookMilestoneEditedChanges {
            description: None,
            due_on: None,
            title: None,
        }
    }
}

