/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookRepositoryRulesetEditedChangesRulesUpdatedInnerChanges {
    #[serde(rename = "configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<Box<models::WebhookOrganizationRenamedChangesLogin>>,
    #[serde(rename = "rule_type", skip_serializing_if = "Option::is_none")]
    pub rule_type: Option<Box<models::WebhookOrganizationRenamedChangesLogin>>,
    #[serde(rename = "pattern", skip_serializing_if = "Option::is_none")]
    pub pattern: Option<Box<models::WebhookOrganizationRenamedChangesLogin>>,
}

impl WebhookRepositoryRulesetEditedChangesRulesUpdatedInnerChanges {
    pub fn new() -> WebhookRepositoryRulesetEditedChangesRulesUpdatedInnerChanges {
        WebhookRepositoryRulesetEditedChangesRulesUpdatedInnerChanges {
            configuration: None,
            rule_type: None,
            pattern: None,
        }
    }
}

