/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookDiscussionTransferredChanges {
    #[serde(rename = "new_discussion")]
    pub new_discussion: Box<models::Discussion>,
    #[serde(rename = "new_repository")]
    pub new_repository: Box<models::RepositoryWebhooks>,
}

impl WebhookDiscussionTransferredChanges {
    pub fn new(new_discussion: models::Discussion, new_repository: models::RepositoryWebhooks) -> WebhookDiscussionTransferredChanges {
        WebhookDiscussionTransferredChanges {
            new_discussion: Box::new(new_discussion),
            new_repository: Box::new(new_repository),
        }
    }
}

