/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookProjectsV2ItemEditedChangesOneOf {
    #[serde(rename = "field_value")]
    pub field_value: Box<models::WebhookProjectsV2ItemEditedChangesOneOfFieldValue>,
}

impl WebhookProjectsV2ItemEditedChangesOneOf {
    pub fn new(field_value: models::WebhookProjectsV2ItemEditedChangesOneOfFieldValue) -> WebhookProjectsV2ItemEditedChangesOneOf {
        WebhookProjectsV2ItemEditedChangesOneOf {
            field_value: Box::new(field_value),
        }
    }
}

