/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookPersonalAccessTokenRequestApproved {
    #[serde(rename = "action")]
    pub action: Action,
    #[serde(rename = "personal_access_token_request")]
    pub personal_access_token_request: Box<models::PersonalAccessTokenRequest>,
    #[serde(rename = "organization")]
    pub organization: Box<models::OrganizationSimpleWebhooks>,
    #[serde(rename = "sender")]
    pub sender: Box<models::SimpleUserWebhooks>,
    #[serde(rename = "installation")]
    pub installation: Box<models::SimpleInstallation>,
}

impl WebhookPersonalAccessTokenRequestApproved {
    pub fn new(action: Action, personal_access_token_request: models::PersonalAccessTokenRequest, organization: models::OrganizationSimpleWebhooks, sender: models::SimpleUserWebhooks, installation: models::SimpleInstallation) -> WebhookPersonalAccessTokenRequestApproved {
        WebhookPersonalAccessTokenRequestApproved {
            action,
            personal_access_token_request: Box::new(personal_access_token_request),
            organization: Box::new(organization),
            sender: Box::new(sender),
            installation: Box::new(installation),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "approved")]
    Approved,
}

impl Default for Action {
    fn default() -> Action {
        Self::Approved
    }
}

