/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookMemberEditedChanges : The changes to the collaborator permissions
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookMemberEditedChanges {
    #[serde(rename = "old_permission", skip_serializing_if = "Option::is_none")]
    pub old_permission: Option<Box<models::WebhookMemberEditedChangesOldPermission>>,
    #[serde(rename = "permission", skip_serializing_if = "Option::is_none")]
    pub permission: Option<Box<models::WebhookMemberEditedChangesPermission>>,
}

impl WebhookMemberEditedChanges {
    /// The changes to the collaborator permissions
    pub fn new() -> WebhookMemberEditedChanges {
        WebhookMemberEditedChanges {
            old_permission: None,
            permission: None,
        }
    }
}

