/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookLabelEditedChangesDescription {
    /// The previous version of the description if the action was `edited`.
    #[serde(rename = "from")]
    pub from: String,
}

impl WebhookLabelEditedChangesDescription {
    pub fn new(from: String) -> WebhookLabelEditedChangesDescription {
        WebhookLabelEditedChangesDescription {
            from,
        }
    }
}

