/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookIssuesOpenedChanges {
    #[serde(rename = "old_issue", deserialize_with = "Option::deserialize")]
    pub old_issue: Option<Box<models::Issue6>>,
    #[serde(rename = "old_repository")]
    pub old_repository: Box<models::Repository1>,
}

impl WebhookIssuesOpenedChanges {
    pub fn new(old_issue: Option<models::Issue6>, old_repository: models::Repository1) -> WebhookIssuesOpenedChanges {
        WebhookIssuesOpenedChanges {
            old_issue: if let Some(x) = old_issue {Some(Box::new(x))} else {None},
            old_repository: Box::new(old_repository),
        }
    }
}

