/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookIssuesEditedChanges : The changes to the issue.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookIssuesEditedChanges {
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<Box<models::WebhooksChangesBody>>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<Box<models::WebhookIssuesEditedChangesTitle>>,
}

impl WebhookIssuesEditedChanges {
    /// The changes to the issue.
    pub fn new() -> WebhookIssuesEditedChanges {
        WebhookIssuesEditedChanges {
            body: None,
            title: None,
        }
    }
}

