/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhooksSecurityAdvisoryCwesInner {
    #[serde(rename = "cwe_id")]
    pub cwe_id: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl WebhooksSecurityAdvisoryCwesInner {
    pub fn new(cwe_id: String, name: String) -> WebhooksSecurityAdvisoryCwesInner {
        WebhooksSecurityAdvisoryCwesInner {
            cwe_id,
            name,
        }
    }
}

