/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookSponsorshipEditedChanges {
    #[serde(rename = "privacy_level", skip_serializing_if = "Option::is_none")]
    pub privacy_level: Option<Box<models::WebhookSponsorshipEditedChangesPrivacyLevel>>,
}

impl WebhookSponsorshipEditedChanges {
    pub fn new() -> WebhookSponsorshipEditedChanges {
        WebhookSponsorshipEditedChanges {
            privacy_level: None,
        }
    }
}

