/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkflowRunUsage : Workflow Run Usage
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowRunUsage {
    #[serde(rename = "billable")]
    pub billable: Box<models::WorkflowRunUsageBillable>,
    #[serde(rename = "run_duration_ms", skip_serializing_if = "Option::is_none")]
    pub run_duration_ms: Option<i32>,
}

impl WorkflowRunUsage {
    /// Workflow Run Usage
    pub fn new(billable: models::WorkflowRunUsageBillable) -> WorkflowRunUsage {
        WorkflowRunUsage {
            billable: Box::new(billable),
            run_duration_ms: None,
        }
    }
}

