/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowRunUsageBillable {
    #[serde(rename = "UBUNTU", skip_serializing_if = "Option::is_none")]
    pub ubuntu: Option<Box<models::WorkflowRunUsageBillableUbuntu>>,
    #[serde(rename = "MACOS", skip_serializing_if = "Option::is_none")]
    pub macos: Option<Box<models::WorkflowRunUsageBillableUbuntu>>,
    #[serde(rename = "WINDOWS", skip_serializing_if = "Option::is_none")]
    pub windows: Option<Box<models::WorkflowRunUsageBillableUbuntu>>,
}

impl WorkflowRunUsageBillable {
    pub fn new() -> WorkflowRunUsageBillable {
        WorkflowRunUsageBillable {
            ubuntu: None,
            macos: None,
            windows: None,
        }
    }
}

