/*
 * GitHub's official OpenAPI spec + Octokit extension
 *
 * OpenAPI specs from https://github.com/github/rest-api-description with the 'x-octokit' extension required by the Octokit SDKs
 *
 * The version of the OpenAPI document: 16.6.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowRunUsageBillableUbuntuJobRunsInner {
    #[serde(rename = "job_id")]
    pub job_id: i32,
    #[serde(rename = "duration_ms")]
    pub duration_ms: i32,
}

impl WorkflowRunUsageBillableUbuntuJobRunsInner {
    pub fn new(job_id: i32, duration_ms: i32) -> WorkflowRunUsageBillableUbuntuJobRunsInner {
        WorkflowRunUsageBillableUbuntuJobRunsInner {
            job_id,
            duration_ms,
        }
    }
}

